#pragma once

#define POP_SIZE 1000
#define SAMPLE_SIZE 400
#define WINNING_SIZE 20
#define LOOSING_SIZE 20
#define CHROMOSOME_LENGTH 50

#define NEXUS_LIMIT 5
#define FORGE_LIMIT 2
#define GATEWAY_LIMIT 50

#define FRAMECOUNT_LIMIT 24 * 60 * 20
